### ISSUE TITLE
Cover customization

### ISSUE THREAD

**Issue by XellossMetallium** [MangaRack/mangarack#16]
I suppose this feature is a bit too specific and of little interest for many, if so please consider this not a feature request but a simple question on how to achieve a similar result with external software.

Since a very nice website called manga covers database is now closed and I didn't want to let all that covers go to waste now I have more than 60gb of covers on my drive. When a serie is complete I usually manually compress the chapters into volumes to better archive it (mangatraders was a great help with this). 

I was thinking of how to put these covers to good use also for the "automatic" part of my library.. now, since mangarack renames the images inside the cbz and 000.jpg is always the cover downloaded from the server, the customization I'm speaking of would be to have mangarack to check the series folders for "V01.cover.jpg", "V02.cover.jpg" and something like "default.cover.jpg" and automatically use that file when the relevant metadata (Volume field) corresponds. 
In any other case it should use default.cover.jpg. Only if that is missing the LQ server one would be applied. Something like that. 

As always I lack the technical knowledge to say if this would be too hard to achieve. From what little I could imagine I'd say that the aggravating part would be to check the already downloaded chapters for changes, if by chance one should add only in a second moment the cover (as obviously it would be if this feature would be implemented). I'll leave it at that for now. :) thanks as always!

**Comment by Deathspike** [comment]
We'd just have to check if a file exists and use that instead of the default cover.

This shouldn't be too much trouble to add. I'll add this to my "nice to have"-things list.

If someone else wants to implement this, look into nodejs/agent/add for an override.

**Comment by XellossMetallium** [comment]
Thanks! Surely it is not critical, but also nice :)
Anyway my doubt was about the chapters already downloaded. If the cover is only available in a second moment and only then I add the image in the folder wouldn't mangarack have to decompress each cbz (at least the first time) to compare the 000.jpg file inside to the external jpg end eventually update it?

**Comment by Deathspike** [comment]
Sure, but there would be a flag to control that.

By default the cover only gets used for new archives. If you use `--force` (example flag) it would inspect, too.

**Comment by XellossMetallium** [comment]
Neat! Thanks for clarifying! :)

**Comment by Deathspike** [comment]
This no longer applies to the `4.0.0` philosophy and is no longer under consideration/up for grabs.
