### ISSUE TITLE
Kissmanga enforcing cookies right now

### ISSUE THREAD

**Issue by warmwaffles** [MangaRack/mangarack#19]
Currently if you run `mangarack` for kissmanga, you will encounter the following.

```sh
bin/mangarack http://kissmanga.com/Manga/Aflame-Inferno
Error: No series: http://kissmanga.com/Manga/Aflame-Inferno
    at /Users/warmwaffles/code/warmwaffles/mangarack.js/lib/nodejs/index.js:178:39
    at /Users/warmwaffles/code/warmwaffles/mangarack.js/lib/nodejs/request.js:65:5
    at /Users/warmwaffles/code/warmwaffles/mangarack.js/lib/nodejs/request.js:33:5
    at IncomingMessage.<anonymous> (/Users/warmwaffles/code/warmwaffles/mangarack.js/lib/nodejs/request.js:96:9)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:907:16
    at process._tickCallback (node.js:372:11)
```

this is the landing page we are hit with: https://gist.github.com/warmwaffles/306bea68428095fa8dbd

The point of interest to get around this is this form:

```html
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="995acb720319e032e0f5b236f91f1662"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
```

and this bit of javascript they try to be tricky with

```js
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var t,r,a,f, lpjTjtZ={"h":+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;lpjTjtZ.h-=+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]));lpjTjtZ.h*=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]));lpjTjtZ.h-=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]));lpjTjtZ.h+=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]));lpjTjtZ.h*=+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));lpjTjtZ.h+=+!![];a.value = parseInt(lpjTjtZ.h, 10) + t.length;
        f.submit();
      }, 5850);
    }, false);
  })();
```

I'm going to poke around in here @Deathspike to see if I can get a fix for it. I have a nice feeling that they are doing this to stop the screen scraping problem and it will be nothing but a cat and mouse game. May need to think of a robust solution that we can use and not have to change code a whole lot when something on their end changes.

**Comment by warmwaffles** [comment]
If you submit that form bit as a git request, you can bypass their little check. At least that's from what I gathered for this short amount of time.

**Comment by warmwaffles** [comment]
```js
var lpjTjtZ = {
  // 47
  h: +((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])) 
};

// -= 26
lpjTjtZ.h -= +((!+[] + !![] + []) + (!+[] + !![] + !![] + !![] + !![] + !![])); 

// *= 46
lpjTjtZ.h *= +((!+[] + !![] + !![] + !![] + []) + (!+[] + !![] + !![] + !![] + !![] + !![])); 

// -= 34
lpjTjtZ.h -= +((!+[] + !![] + !![] + []) + (!+[] + !![] + !![] + !![])); 

// += 34
lpjTjtZ.h += +((!+[] + !![] + !![] + []) + (!+[] + !![] + !![] + !![]));

// *= 29
lpjTjtZ.h *= +((!+[] + !![] + []) + (!+[] + !![] + !![] + !![] + !![] + !![] + !![] + !![] + !![]));

// += 1
lpjTjtZ.h += +!![];

// a.value = 28015 + t.length
a.value = parseInt(lpjTjtZ.h, 10) + t.length;
```

**Comment by Deathspike** [comment]
Thanks!

The challenge contents appear to differ each time. I presume they generate some kind of secret in the session and generate some JavaScript challenge on the fly (I just got `327 + t.length`). That basically means we'd either have to parse the JavaScript and execute it (we can do that inside a Virtual Machine, for instance) or just use a browser to let the code run without caring about what it is at all (e.g. with the use of PhantomJS). I have no idea why they added a timeout, though, it just makes the entire thing more annoying for regular users.

**Comment by Deathspike** [comment]
This is the  solution I came up with (to avoid hacking around their ever-changing "validation"):

	'use strict';
	var args = require('system').args;
	var isAuthenticating = false;
	var page = require('webpage').create();
	page.open(args[1]);

	page.onError = function () {
	  return;
	};

	page.onInitialized = function () {
	  page.evaluate(function () {
		window.navigator = {
		  appName: 'Netscape',
		  vendor: 'Google Inc.'
		};
	  });
	};

	page.onLoadFinished = function(status) {
	  if (isAuthenticating) {
		console.log(JSON.stringify(getCookies(), null, '  '));
		return setTimeout(phantom.exit, 0);
	  }
	  isAuthenticating = true;
	};

	/**
	 * Retrieves interesting cookies.
	 * @returns {!Array.<!Object>}
	 */
	function getCookies() {
	  var cookies = [];
	  Object.keys(phantom.cookies).forEach(function (key) {
		var cookie = phantom.cookies[key];
		if (!/kissmanga.com$/.test(cookie.domain)) return;
		cookies.push(cookie);
	  });
	  return cookies;
	}

So we can invoke this with `phantomjs` and get a nice print of cookies:

	phantomjs kiss.js http://kissmanga.com/Manga/Candy-Boy

I'll be integrating this sometime soon I suppose, unless there are further comments on this? :-)

**Comment by warmwaffles** [comment]
It looks like kissmanga removed their _hack_ for stopping scraping.

**Comment by Deathspike** [comment]
Good!

It was annoying for users, and search engines can't do much with it either. I'll leave this issue to serve as future reminder to get around any kind of browser test. I'm actually a little happy I was swamped with work and didn't get around to implementing it until today. We can use this approach in the future, and *future me* should consider:

* Blocking requests to non-specific domains (e.g. ads; don't load them in).
* Hijack the `setTimout` function to accelerate dumb checks.

Closed for now. Thanks for the update @warmwaffles

**Comment by pbatard** [comment]
> It looks like kissmanga removed their hack for stopping scraping.

It looks like kissmanga added their hack back again. I tried to play with adding the relevant cookies manually in `request.js`, but no luck so far... :disappointed: 

Would appreciate if the kissmanga cookie workaround could be integrated.

**Comment by Deathspike** [comment]
A minor update on this issue to all those who are subscribed to this issue:

I have completed support for KissManga crawler protection in the 4.0 branch. It is currently undergoing some additional testing, but it seems to be pretty stable. The 4.0 branch will soon replace the current 3.0 branch. Your configurations will have to be updated, but expect this support/change to be coming this weekend, or the next.

**Comment by Deathspike** [comment]
And that's live now.

**Comment by pbatard** [comment]
Awesome! :+1: 

I tested the latest and everything looks good. Thank you very much for the quick fix!
