### ISSUE TITLE
Process out of memory

### ISSUE THREAD

**Issue by benbarclay** [MangaRack/mangarack#22]
Fetching Hayate no Gotoku! #305.cbz
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Abort trap: 6

Second time this has happened to me. Only happens after a very large number of downloads.

**Comment by Deathspike** [comment]
Can you provide some additional information?

* NodeJS version
* MangaRack version
* Operating system and architecture (32/64 bits)
* Total system RAM
* Estimated available RAM when this error occurred (excluding MangaRack)

**Comment by benbarclay** [comment]
Don't have my laptop on me, so going off memory here. Can provide better info later. 

Node should be latest stable. 

MangaRack version was the recent one that included kiss manga fix 

OS X 64 bit

Total ram 16gb

Estimated ram available would have been about 10gb

**Comment by Deathspike** [comment]
Going to close this. No longer relevant with the complete rewrite that was 4.0.

Please feel free to re-open if this occurs again.
