### ISSUE TITLE
New command: reading direction

### ISSUE THREAD

**Issue by XellossMetallium** [MangaRack/mangarack#31]
To proper support not japanese releases (yet right to left should be the default behavior) maybe a command like --lefttoright or --occidental could be implemented to manually chose when to not attach the right to left tag :)

**Comment by Deathspike** [comment]
I've chosen *not* to implement this. However, the `4.0.0` branch does have additional fixes that solves incorrect reading directions for series on `kissmanga` and `batoto`. Unlike `mangafox`, they represent the type of series through tags, so we now scan the tags and take appropriate action when applicable.
