### ISSUE TITLE
More of a 'help me' post...

### ISSUE THREAD

**Issue by damidget** [MangaRack/mangarack#37]
I am in need of migrating over the the new version (v4.0).
Can you please give me an example (if it's at all still possible) to read a list of manga from a file, then save to a designated directory?
e.g. I was previously using...
```
call %AppData%\npm\mangarack -j -o E:\MangaRack\Files\Manga -s E:\MangaRack\Files\MangaList.txt
```
Thanks in advance.
P.S. This is my current, out of date, batch file:
```
call npm update -g mangarack
call %AppData%\npm\mangarack -j -o E:\MangaRack\Files\Manga -s E:\MangaRack\Files\MangaList.txt
call %AppData%\npm\mangarack -j -o E:\MangaRack\Files\Webtoons -s E:\MangaRack\Files\WebtoonsList.txt
call %AppData%\npm\mangarack -j -o E:\MangaRack\Files\Manga -s E:\MangaRack\Files\CompleteMangaList.txt
call %AppData%\npm\mangarack -j -o E:\MangaRack\Files\Webtoons -s E:\MangaRack\Files\CompleteWebtoonsList.txt
pause
```
P.P.S. I have tried to resolve this myself, but am failing to understand what I need to do.

**Comment by XellossMetallium** [comment]
Here an example for batoto (which requires access data), for others the two commands are not needed:

call %AppData%\npm\mangarack-cli --component.core.batoto.username USERNAME --component.core.batoto.password PASSWORD < batoto.txt

Txt file should be in the same directory of the .bat file (actually I haven't tried if a path, like "< subfolder\batoto.txt", can be attached).
Output cannot be provided, the command is deprecated. Simply put the .bat in the folder you want to use (or run the command in the directory you want to download into). 
Something missing?

**Comment by damidget** [comment]
Does this mean anything to you? Even after doing the changes you suggested (of which I'd tried before) I still get this message.

```
E:\MangaRack\Files\Manga>call C:\Users\midge\AppData\Roaming\npm\mangarack-cli  0<MangaList.txt
C:\Users\midge\AppData\Roaming\npm\node_modules\mangarack\dist\cli.js:13
let dependencies = {};
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\midge\AppData\Roaming\npm\node_modules\mangarack\bin\mangarack-cli:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

bat file:
```
call %AppData%\npm\mangarack-cli < MangaList.txt
pause
```

I am also getting the same response if I try:
```
call %AppData%\npm\mangarack-cli http://mangafox.me/manga/ajin
pause
```

Did you have to reinstall anything when you changed from version 3.x to 4.x, XellossMetallium?

**Comment by XellossMetallium** [comment]
I simply updated, without the need to reinstall anything. 
Sadly I do not have the knowledge to understand what error it is: I can only say that if the installation path of mangarack is correct your bat file should work, so we'll have to wait for @Deathspike and see.

**Comment by Deathspike** [comment]
I'm going to break down this line:

    call %AppData%\npm\mangarack -j -o E:\MangaRack\Files\Manga -s E:\MangaRack\Files\MangaList.txt

The `-o` changes output directory, so we have to do this using the regular `change directory`:

    cd E:\MangaRack\Files\Manga

The `-s` indicated that a file was read and processed, but `4.x` used *stdin*, so we can do:

   call %AppData%\npm\mangarack < E:\MangaRack\Files\MangaList.txt

The `-j` switch is dropped, so you would end up with:

   cd E:\MangaRack\Files\Manga
   call %AppData%\npm\mangarack < E:\MangaRack\Files\MangaList.txt

Since *bat* is just line-by-line execution, you can change your *bat* file easily for this.

Regarding "SyntaxError: Unexpected strict mode reserved word"; update NodeJS to `5.x`.

**Comment by damidget** [comment]
Ah, I accidentally updated to the other version of NodeJS on their website.

Thanks for dumbing it all down for me, Deathspike!
